export const LAYOUT_SIDEBAR_TOGGLE = 'LAYOUT_SIDEBAR_TOGGLE';

export const SEARCH_QUERY_CHANGE = 'SEARCH_QUERY_CHANGE';
export const SEARCH_DOMAIN_CHANGE = 'SEARCH_DOMAIN_CHANGE';
export const SEARCH_BEGIN = 'SEARCH_BEGIN';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';

export const LOAD_EVENT_DETAILS_SUCCESS = 'LOAD_EVENT_DETAILS_SUCCESS';

export const LOAD_EVENTS_BEGIN = 'LOAD_EVENTS_BEGIN';
export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
export const LOAD_CAMPS_BEGIN = 'LOAD_CAMPS_BEGIN';
export const LOAD_CAMPS_SUCCESS = 'LOAD_CAMPS_SUCCESS';
export const LOAD_ARTS_BEGIN = 'LOAD_ARTS_BEGIN';
export const LOAD_ARTS_SUCCESS = 'LOAD_ARTS_SUCCESS';
